### PR TITLE
Add Travis CI integration

### PR DESCRIPTION
**Pull request by danstn**
This PR Build Status: 

[Build Status](https://travis-ci.org/danstn/elm-postgrest)

... and a "self-documenting" Makefile:

``` bash
$ make
install    Install build dependencies and packages
build      Build
test       Run unit tests
```

For #4.

### CODE REVIEW

**Comment by danstn** [comment]
Should probably use a specific version of Node instead ([example travis setup](https://github.com/rtfeldman/elm-css/blob/6ba8404f53269bc110c2e08ab24c9caf850da515/.travis.yml)).

**Comment by john-kelly** [comment]
Great. I'll take a look tonight after work. 👍  for using elm-css as a guide.

**Comment by john-kelly** [comment]
Additionally, what are your thoughts on this travis setup: https://github.com/krisajenkins/remotedata

I'd be happy to _not_ introduce `node-test-runner` if we don't have to. I suppose it's not that big of a deal though. 

I'll keep playing with this though and let you know what I think.

**Comment by danstn** [comment]
That exactly where I started: https://github.com/john-kelly/elm-postgrest/pull/5/commits/534f04341c2b341838c466fa1a3c5dabdc067a87

Test runner blows up on `Promise`s (cause of node version I think).

See this [failing build](https://travis-ci.org/danstn/elm-postgrest/builds/168814554).

Not really sure what's the best way to go about it. `elm-test` worked fine for me in the past so I just went for it.

**Comment by john-kelly** [comment]
I looked at a few more examples and it looks like you implemented the "best practice" test suite. I think this is good to go 👍

**Comment by john-kelly** [comment]
fixes https://github.com/john-kelly/elm-postgrest/issues/4

**Pull request merged**
